In [19]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

from sklearn import preprocessing

In [4]:
students_and_addiction = pd.read_csv("Students Social Media Addiction.csv")

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

Veamos si el dataset tiene datos nulos

In [11]:
students_and_addiction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    object
 3   Academic_Level                705 non-null    object
 4   Country                       705 non-null    object
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    object
 7   Affects_Academic_Performance  705 non-null    object
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    object
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
dtypes: float64(2), int64(5), object(6)
memory usage: 71.7+ KB

In [12]:
students_and_addiction.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000

In [13]:
students_and_addiction_copy = students_and_addiction.copy()
students_and_addiction_copy.replace("Yes", 1, inplace=True)
students_and_addiction_copy.replace("No", 0, inplace=True)

students_and_addiction_copy2 = students_and_addiction_copy.drop(["Gender", "Academic_Level", "Country", "Most_Used_Platform", "Relationship_Status"], axis = 1)

students_and_addiction_copy2.corr()

C:\Users\SebastiÃ¡n\AppData\Local\Temp\ipykernel_16924\1545354173.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  students_and_addiction_copy.replace("No", 0, inplace=True)

,Student_ID,Age,Avg_Daily_Usage_Hours,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
Student_ID,1.000000,0.222306,0.267524,0.053780,0.173793,-0.055037,0.173258,0.041637
Age,0.222306,1.000000,-0.113682,-0.137140,0.125265,0.160278,-0.184482,-0.166396
Avg_Daily_Usage_Hours,0.267524,-0.113682,1.000000,0.661474,-0.790582,-0.801058,0.804582,0.832000
Affects_Academic_Performance,0.053780,-0.137140,0.661474,1.000000,-0.625373,-0.808921,0.832030,0.866049
Sleep_Hours_Per_Night,0.173793,0.125265,-0.790582,-0.625373,1.000000,0.707439,-0.677266,-0.764858
Mental_Health_Score,-0.055037,0.160278,-0.801058,-0.808921,0.707439,1.000000,-0.893572,-0.945051
Conflicts_Over_Social_Media,0.173258,-0.184482,0.804582,0.832030,-0.677266,-0.893572,1.000000,0.933586
Addicted_Score,0.041637,-0.166396,0.832000,0.866049,-0.764858,-0.945051,0.933586,1.000000

Entonces vemos que hay una correlaciÃ³n entre Avg_Daily_Usage_Hours y Mental_Health_Score, donde ambas variables son inversamente proporcionales. A su vez Addicted_Score es inversamente proporcional a Mental_Health_Score. Por ende al menos en base mientras mayor sea la adicciÃ³n o la cantidad de horas que se invierten al dÃ­a en redes sociales, menor serÃ¡ la salud mental

In [14]:
students_and_addiction["Country"].unique()

array(['Bangladesh', 'India', 'USA', 'UK', 'Canada', 'Australia',
       'Germany', 'Brazil', 'Japan', 'South Korea', 'France', 'Spain',
       'Italy', 'Mexico', 'Russia', 'China', 'Sweden', 'Norway',
       'Denmark', 'Netherlands', 'Belgium', 'Switzerland', 'Austria',
       'Portugal', 'Greece', 'Ireland', 'New Zealand', 'Singapore',
       'Malaysia', 'Thailand', 'Vietnam', 'Philippines', 'Indonesia',
       'Taiwan', 'Hong Kong', 'Turkey', 'Israel', 'UAE', 'Egypt',
       'Morocco', 'South Africa', 'Nigeria', 'Kenya', 'Ghana',
       'Argentina', 'Chile', 'Colombia', 'Peru', 'Venezuela', 'Ecuador',
       'Uruguay', 'Paraguay', 'Bolivia', 'Costa Rica', 'Panama',
       'Jamaica', 'Trinidad', 'Bahamas', 'Iceland', 'Finland', 'Poland',
       'Romania', 'Hungary', 'Czech Republic', 'Slovakia', 'Croatia',
       'Serbia', 'Slovenia', 'Bulgaria', 'Estonia', 'Latvia', 'Lithuania',
       'Ukraine', 'Moldova', 'Belarus', 'Kazakhstan', 'Uzbekistan',
       'Kyrgyzstan', 'Tajikistan', 'Armenia', 'Georgia', 'Azerbaijan',
       'Cyprus', 'Malta', 'Luxembourg', 'Monaco', 'Andorra', 'San Marino',
       'Vatican City', 'Liechtenstein', 'Montenegro', 'Albania',
       'North Macedonia', 'Kosovo', 'Bosnia', 'Qatar', 'Kuwait',
       'Bahrain', 'Oman', 'Jordan', 'Lebanon', 'Iraq', 'Yemen', 'Syria',
       'Afghanistan', 'Pakistan', 'Nepal', 'Bhutan', 'Sri Lanka',
       'Maldives'], dtype=object)

Definimos la variables X y la variable que queremos explicar (Mental_Health_Score)

In [26]:
X = students_and_addiction.drop("Mental_Health_Score", axis = 1)
y = students_and_addiction["Mental_Health_Score"]

# CodificaciÃ³n
one_hot_encoded = pd.get_dummies(X, columns=["Gender", "Academic_Level", "Country", "Most_Used_Platform", "Relationship_Status"])

X_encoded = one_hot_encoded
print(one_hot_encoded)

X_encoded.replace("Yes", 1, inplace=True)
X_encoded.replace("No", 0, inplace=True)


X_encoded = X_encoded.astype(int)

min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X_encoded)
X

     Student_ID  Age  Avg_Daily_Usage_Hours Affects_Academic_Performance  \
0             1   19                    5.2                          Yes
1             2   22                    2.1                           No
2             3   20                    6.0                          Yes
3             4   18                    3.0                           No
4             5   21                    4.5                          Yes
..          ...  ...                    ...                          ...
700         701   20                    4.7                           No
701         702   23                    6.8                          Yes
702         703   21                    5.6                          Yes
703         704   24                    4.3                           No
704         705   19                    6.2                          Yes

     Sleep_Hours_Per_Night  Conflicts_Over_Social_Media  Addicted_Score  \
0                      6.5                            3               8
1                      7.5                            0               3
2                      5.0                            4               9
3                      7.0                            1               4
4                      6.0                            2               7
..                     ...                          ...             ...
700                    7.2                            2               5
701                    5.9                            5               9
702                    6.7                            3               7
703                    7.5                            2               4
704                    6.3                            4               8

     Gender_Female  Gender_Male  Academic_Level_Graduate  ...  \
0             True        False                    False  ...
1            False         True                     True  ...
2             True        False                    False  ...
3            False         True                    False  ...
4            False         True                     True  ...
..             ...          ...                      ...  ...
700           True        False                    False  ...
701          False         True                     True  ...
702           True        False                    False  ...
703          False         True                     True  ...
704           True        False                    False  ...

     Most_Used_Platform_Snapchat  Most_Used_Platform_TikTok  \
0                          False                      False
1                          False                      False
2                          False                       True
3                          False                      False
4                          False                      False
..                           ...                        ...
700                        False                       True
701                        False                      False
702                        False                      False
703                        False                      False
704                        False                      False

     Most_Used_Platform_Twitter  Most_Used_Platform_VKontakte  \
0                         False                         False
1                          True                         False
2                         False                         False
3                         False                         False
4                         False                         False
..                          ...                           ...
700                       False                         False
701                       False                         False
702                       False                         False
703                        True                         False
704                       False                         False

     Most_Used_Platform_WeChat  Most_Used_Platform_WhatsApp  \
0                        False                        False
1                        False                        False
2                        False                        False
3                        False                        False
4                        False                        False
..                         ...                          ...
700                      False                        False
701                      False                        False
702                       True                        False
703                      False                        False
704                      False                        False

     Most_Used_Platform_YouTube  Relationship_Status_Complicated  \
0                         False                            False
1                         False                            False
2                         False                             True
3                          True                            False
4                         False                            False
..                          ...                              ...
700                       False                            False
701                       False                            False
702                       False                            False
703                       False                            False
704                       False                            False

     Relationship_Status_In Relationship  Relationship_Status_Single
0                                   True                       False
1                                  False                        True
2                                  False                       False
3                                  False                        True
4                                   True                       False
..                                   ...                         ...
700                                 True                       False
701                                False                        True
702                                 True                       False
703                                False                        True
704                                False                        True

[705 rows x 137 columns]

C:\Users\SebastiÃ¡n\AppData\Local\Temp\ipykernel_16924\2596402159.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_encoded.replace("No", 0, inplace=True)

array([[0.        , 0.16666667, 0.57142857, ..., 0.        , 1.        ,
        0.        ],
       [0.00142045, 0.66666667, 0.14285714, ..., 0.        , 0.        ,
        1.        ],
       [0.00284091, 0.33333333, 0.71428571, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.99715909, 0.5       , 0.57142857, ..., 0.        , 1.        ,
        0.        ],
       [0.99857955, 1.        , 0.42857143, ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.16666667, 0.71428571, ..., 0.        , 0.        ,
        1.        ]])